package net.hdhuu.splee.splitter

class SplittestHelper {

    object Data {
      val happyCaseMessage = "I can't believe Tweeter now supports chunking my messages, so I don't have to do it myself."
        val shortMessage = "This article is about god"
        val inputMessageTest =
            " This article is about the organisation within the BBC. For the television channel, see BBC News (TV channel). For other uses, see BBC News (disambiguation). BBC News BBC News.svg Type BBC department Industry Broadcast media Headquarters BBC Television Centre (1969–2013) Broadcasting House (2012–), London, England Area served Specific services for United Kingdom and rest of world Key people Fran Unsworth (Director of News & Current Affairs) Mary Hockaday (Head of Newsroom) Huw Edwards (Chief Presenter) Services Radio, internet, and television broadcasts Owner BBC Number of employees 3,500 (2,000 are journalists) Website BBC News BBC News is an operational business division[1] of the British Broadcasting Corporation (BBC) responsible for the gathering and broadcasting of news and current affairs. The department is the world's largest broadcast news organisation and generates about 120 hours of radio and television output each day, as well as online news coverage.[2][3] The service maintains 50 foreign news bureaus with more than 250 correspondents around the world.[4] Fran Unsworth has been Director of News and Current Affairs since January 2018.[5][6] The department's annual budget is in excess of £350 million; it has 3,500 staff, 2,000 of whom are journalists.[2] BBC News' domestic, global and online news divisions are housed within the largest live newsroom in Europe, in Broadcasting House in central London. Parliamentary coverage is produced and broadcast from studios in Millbank in London. Through the BBC English Regions, the BBC also has regional centres across England, as well as national news centres in Northern Ireland, Scotland and Wales. All nations and English regions produce their own local news programmes and other current affairs and sport programmes. The BBC is Data quasi-autonomous corporation authorised by Royal Charter, making it operationally independent of the government, who have no power to appoint or dismiss its director-general, and required to report impartially. As with all major media outlets it has been accused of political bias from across the political spectrum, both within the UK and abroad."
    }
}